### ISSUE TITLE
Nils roadmap

### ISSUE THREAD

**Issue by Didgy74** [Didgy74/computer-vision#2]
- [ ] Read up on saturation from the book, research how we can improve the metric
- [ ] Look into measuring ranges of saturation
- [ ] Look into how to measure the metric on only the images where saturation is affected by the distortion
- [ ] Write up findings in the report
